server:
  port: 8888

spring:
  cloud:
    config:
      server:
        bootstrap: true
        git:
            default-label: main
            uri: https://github.com/deeptaste/miu-git-config-repo

management:
  endpoint:
    web:
      exposure:
        include: '*'
