server:
  port: 8085

spring:
  application:
    name: product-service
  cloud:
    config:
      enabled: true
  config:
    import: optional:configserver:http://localhost:8888
#  profiles:
#    active: dev

management:
  endpoint:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
