server:
  port: 8084

spring:
  application:
    name: user-service
  cloud:
    config:
      enabled: true
  config:
    import: optional:configserver:http://localhost:8888

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always


